---
name: vault

instance_groups:
- instances: ((VAULT_INSTANCES))
  name: vault
  networks: [{name: ((VAULT_NW_NAME)), static_ips: [((STATIC_IPS))], default: [dns, gateway]}]
  persistent_disk_type: ((VAULT_DISK_TYPE))
  vm_type: ((VAULT_VM_TYPE))
  stemcell: trusty
  azs: [((VAULT_AZ_NAME))]
  jobs:
  - name: vault
    release: vault
    properties:
      vault:
        storage:
          use_consul: true

  - name: consul
    release: consul
    provides:
      consul_servers: { as: consul_leaders }
    consumes:
      consul_servers: { from: consul_leaders }
    properties:
      consul:
        join_hosts: [((STATIC_IPS))]

releases:
- name: vault
  version: latest
- name: consul
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-30000
