---
azs:
- name: ((az_name))
  cloud_properties:
    datacenters:
    - clusters: [((vcenter_cluster)): {}]

networks:
- name: ((nw_name))
  type: manual
  subnets:
  - range: ((network_cidr))
    dns: [((dns_servers))]
    gateway: ((network_gateway))
    azs: [((az_name))]
    cloud_properties:
      name: ((network_name))
    reserved: ((reserved_ips))
    static: [((static_ips))]

vm_types:
- name: micro.disk
  cloud_properties:
    ram: 1024
    cpu: 1
    disk: 8192
- name: small.disk
  cloud_properties:
    ram: 1024
    cpu: 1
    disk: 10240
- name: medium.disk
  cloud_properties:
    ram: 2096
    cpu: 1
    disk: 20480
- name: large.disk
  cloud_properties:
    ram: 4096
    cpu: 1
    disk: 102400
- name: xlarge.disk
  cloud_properties:
    ram: 8192
    cpu: 1
    disk: 131072

disk_types:
- name: small
  disk_size: 1024
  cloud_properties:
    type: thick

- name: large
  disk_size: 50_000
  cloud_properties:
    type: thick

- name: xlarge
  disk_size: 10240
  cloud_properties:
    type: thick

compilation:
  workers: 1
  network: ((nw_name))
  az: ((az_name))
  reuse_compilation_vms: true
  vm_type: micro.disk

vm_extensions:
- name: public_ip
  cloud_properties: {}
